marks=[]
f1=int(input("enter the name of the marks: "))
marks.append(f1)
f2=int(input("enter the name of the marks: "))
marks.append(f2)
f3=int(input("enter the name of the marks: "))
marks.append(f3)
f4=int(input("enter the name of the marks: "))
marks.append(f4)
f5=int(input("enter the name of the marks: "))
marks.append(f5)
f6=int(input("enter the name of the marks: "))
marks.append(f6)
marks.sort()
print(marks)
print(sum(marks))
a=[1,2,3,4]
print(sum(a))